name: mgh_client
description: "杂志主页客户端"

version: 1.0.0+1

environment:
  sdk: ^3.10.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  html: ^0.15.6
  crypto: ^3.0.7
  intl: ^0.20.2
  flutter_widget_from_html: ^0.17.1
  date_format: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
     - assets/bg.png
     - assets/icons/

  fonts:
    - family: LXGW-WenKai
      fonts:
        - asset: assets/fonts/LXGWWenKai-Regular.ttf
        - asset: assets/fonts/LXGWWenKai-Medium.ttf
          weight: 500
        - asset: assets/fonts/LXGWWenKai-Light.ttf
          weight: 300
